FROM node:18.12.1-alpine as builder

# Create app directory
WORKDIR /api

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY . .

# Install app dependencies
RUN yarn install


CMD ["yarn", "start:migrate"]

# RUN npm run build

# FROM node:18.12.1-alpine

# # COPY --from=builder /api/node_modules ./node_modules
# # COPY --from=builder /api/package*.json ./
# # COPY --from=builder /api/tsconfig.*.json ./
# # # COPY --from=builder /api/dist ./dist
# # COPY --from=builder /api/prisma ./prisma

# COPY --from=builder /api .

# CMD ["yarn", "start:migrate"]



